# Generated by Django 5.0.3 on 2024-04-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, to='home.rooms'),
        ),
    ]
