# Generated by Django 5.0.3 on 2024-04-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_student_room_student_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
        migrations.AddField(
            model_name='rooms',
            name='students',
            field=models.ManyToManyField(to='home.student'),
        ),
    ]
