# Generated by Django 5.0.3 on 2024-04-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_rooms_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
