# Generated by Django 5.0.3 on 2024-04-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='students',
            field=models.ManyToManyField(related_name='rooms', to='home.student'),
        ),
    ]
