# Generated by Django 5.0.3 on 2024-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rooms_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='home.student'),
        ),
    ]
