# Generated by Django 5.0.3 on 2024-04-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_rooms_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='home.rooms'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
