# Generated by Django 5.0.3 on 2024-04-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_rooms_students_student_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='auto_assign_all_rooms',
            field=models.BooleanField(default=False),
        ),
    ]
