# Generated by Django 5.0.3 on 2024-04-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_student_auto_assign_all_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='students',
            field=models.ManyToManyField(related_name='assigned_rooms', to='home.student'),
        ),
    ]
