# Generated by Django 5.0.3 on 2024-04-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_student_email_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
